# Generated by Django 3.1.4 on 2020-12-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executor',
            name='offers',
            field=models.ManyToManyField(related_name='executors', through='market.Payment', to='market.Position'),
        ),
    ]
