# Generated by Django 3.1.4 on 2020-12-03 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('okpd2', models.CharField(max_length=20)),
                ('okei', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='market.request')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmp', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executors', to='users.executor')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='market.position')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Created', 'Created'), ('Assigned', 'Assigned to the executer'), ('Paid', 'Payment issued'), ('Returned', 'Returned to the executor'), ('Canceled', 'executor removed from payment'), ('Expired', 'Expired')], max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.TextField()),
                ('executor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.executor')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='market.position')),
            ],
        ),
        migrations.AddConstraint(
            model_name='changehistory',
            constraint=models.CheckConstraint(check=models.Q(stage__in=['Created', 'Assigned', 'Paid', 'Returned', 'Canceled', 'Expired']), name='market_changehistory_stage_valid'),
        ),
    ]
