# Generated by Django 3.1.4 on 2020-12-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201204_1240'),
        ('market', '0002_auto_20201204_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changehistory',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.executor'),
        ),
    ]
